Update source and test
timeplus-io/gluon pull request #84
Opened 2023-08-16 20:38 UTC by jingyaokang

Create source.py;
Update test for type generator;

2023-08-17 18:43 UTC, jingyaokang commented
Update test for type kafka

2023-08-18 15:36 UTC, gangtao commented on python/test/test_source.py
> +    try:
one improvement here is that you can call stream.exist() to check if the stream already exist, if yes, delete it and recreate.

2023-08-18 15:38 UTC, gangtao commented on python/test/test_source.py
> +
before, delete, to make sure source is running, you need to run a query on the stream to valid the source is generating new data on that stream.

2023-08-18 15:38 UTC, gangtao commented on python/test/test_source.py
> +    "data_type": "text",
formating the json here

2023-08-18 15:39 UTC, gangtao commented on python/test/test_source.py
> +    "sasl": "none",
`sasl = None` instead of `sasl = "none"` ?

2023-08-18 15:40 UTC, gangtao commented on python/timeplus/source.py
> +            # "name": self._name,
you can remove those comments

2023-08-18 15:41 UTC, gangtao commented on python/timeplus/source.py
> +        if self._name:
it is better throw exception in requirement parameter is None

2023-08-18 15:43 UTC, gangtao commented on python/timeplus/source.py
> +    def update(self, source_id, body):
we may need hide the update for now, it is a little bit tricky as some of the property cannot be updated

2023-08-18 15:46 UTC, gangtao commented on python/timeplus/source.py
> +            return False
please consider add start/stop source
https://docs.timeplus.com/rest.html#tag/Sources-v1beta2/paths/~1v1beta2~1sources~1%7Bid%7D~1start/post
https://docs.timeplus.com/rest.html#tag/Sources-v1beta2/paths/~1v1beta2~1sources~1%7Bid%7D~1stop/post

and id() function which return the source id .

2023-08-18 15:51 UTC, gangtao commented on python/timeplus/source.py
> +
we need an id() function to get/set the id

you can refer to this set/get pattern
```
class MyClass:
    def __init__(self):
        self._value = None
    
    def value(self, *args):
        if len(args) == 0:
            print("Getting value...")
            return self._value
        elif len(args) == 1:
            new_value = args[0]
            print("Setting value...")
            self._value = new_value
        else:
            raise ValueError("value() accepts at most 1 argument")
```

2023-08-18 15:55 UTC, gangtao requested changes
please check my comment, overall I think it is good

2023-08-21 17:09 UTC, gangtao approved these changes

2023-08-21 17:19 UTC, merged

2023-09-01 01:58 UTC, jovezhong commented
(Jove Github Bot) added it to the current sprint.

2023-10-27 18:31 UTC, jovezhong commented
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).